### ISSUE TITLE
Dirichlet Boundary Conditions 

### ISSUE THREAD

**Issue by lucentdan** [mesoscale/mmsp#39]
Dirichlet boundary conditions need information that is not currently stored with the grid or that can be derived from the grid.  A means to store/retrieve this information from a grid should be provided by MMSP.  Thoughts on how to do this?  Anyone?  I'm happy to write the code, but some thoughts on design are welcome.

**Comment by lucentdan** [comment]
Actually - I've be thinking a bit more on this.  The user should be able to set the boundary values whenever they want by directly accessing the grid.  The Dirichlet option should just leave things alone (as compared to mirror, etc...).  Still want to chat a bit about this, though.

**Comment by tkphd** [comment]
- As it stands, MMSP assumes whatever value you provide along the boundary in the initial condition is the constant value you want. This is probably the simplest way to handle Dirichlet, and should be valid for most users.
- This problem is more interesting for Neumann boundary conditions, which MMSP forces into zero-flux. Again, this is the simplest way to handle it, but the name is misleading: Neumann is constant-gradient, not zero-gradient.
- One way to address this would be to create derivatives of the ```grid``` class that allocate memory and provide access functions to set the values on the boundary.
- For Dirichlet boundaries, the values can be stored in the adjacent ghost cells. Using these values correctly would take some thought, if the possibility of an initial condition that does not specify the boundary values is desirable. Since true Neumann conditions require a vector-valued definition, we can't just use ghost cells for those boundaries.

**Comment by lucentdan** [comment]
I'm going to close this for now.  Need to fully absorb what you said above.
