### ISSUE TITLE
Error in serial grid constructor in anisotropic solidification example

### ISSUE THREAD

**Issue by fields4242** [mesoscale/mmsp#55]
The grid constructor used on line 53 of `solidification.cpp`, `static grid<dim,T> refGrid(oldGrid,0);`, in the anisotropic solidification example creates non-physical values at several nodes of the grid, regardless of changing grid dimensions and other parameters. This error does not occur when compiling the parallel version.

**Comment by tkphd** [comment]
Thanks for reporting this, @fields4242! There is indeed an error, which can be readily resolved.*
- Line 53 invokes the copy constructor from `MMSP.grid.h:192`, implemented in `MMSP.grid.cpp:101`.
- `template<int dim, typename T> MMSP::grid<dim,T> refGrid(const MMSP::grid<dim,U>& GRID, int FIELDS)` is a *shallow copy* constructor, as are all of MMSP's grid copy constructors: only metadata (size, shape, number of fields) gets copied, not actual data (grid values).
- With `T=double`, `U=MMSP::vector<T>`, and `FIELDS=0`, the invocation on line 53 is technically correct. It builds a scalar-valued grid from a vector-valued one, which is fine, and it sets `FIELDS=0` in the scalar grid.
- A non-zero value of `FIELDS` is only meaningful in `vector`-valued grids: `scalar` and `sparse` grids should set `FIELDS=0` or not at all: the value is disregarded anyway.
- The comment following the invocation is misleading: `field 0` is not copied from `oldGrid`. Space is allocated for just one field, but no data is transferred.
- The values of `refGrid` are not initialized until `solidification.cpp:142-143`, so the access on line 139 is undefined. It's possible the code works because `newGrid` has been constructed and deleted, so the freed memory contains physical values. Anyway, the initial values are garbage.

The fix is fairly simple: copy lines 142 & 143 and paste them at line 54 to initialize the `garbage`-valued `refGrid`. Retain lines 142 & 143 to make sure the `scalar`-valued `refGrid` gets updated.

If you're interested in making this correction, since you found it, please assign yourself and submit a pull request (branch off of `develop`, fix & test, commit, push to your fork on GitHub, visit [origin](https://github.com/mesoscale/mmsp), fill in the form). If you'd rather not, just assign me and I'll do it.

\* I don't know your level of familiarity with MMSP, C++, or GitHub, so this response is somewhat verbose and aimed at a generic contributor. Please bear with me.

**Comment by lucentdan** [comment]
Assigned this to Matt.  

Trevor, Matt can do this!
