### ISSUE TITLE
Reading in files generated on 64-bit machines with a 32-bit machine

### ISSUE THREAD

**Issue by djdcrist** [mesoscale/mmsp#9]
There is a bug with reading 64-bit machine-produced data files on a local 32-bit architecture machine. If, for instance, you generate file.02000.dat on a 64-bit machine, and transfer it to a 32-bit machine and try to convert it to a vti file, you will get a bad_alloc dump. You also run into similar issues trying to compile and run the topology analysis algorithms on 32-bit machines.

**Comment by tkphd** [comment]
This is a low priority, since most machines are 64-bit, and this problem only occurs when transferring data from 64- to 32-bit machines. This could probably be addressed by converting all int -> int32_t and all long -> int64_t, or using a utility function patterned after wrongendian to cast anything greater than 32-bit into a 32-bit equivalent. These simple fixes would fail on arrays larger than 2GB, which would limit MMSP functionality: such arrays are seen in the wild. Suggestions for better approaches are welcome.
